<?xml version="1.0" encoding="ASCII" standalone="yes"?>
<!DOCTYPE top [
	<!ELEMENT top		(project*, employee*)>
	
	<!ELEMENT project	(goal, team_member+)>
	<!ATTLIST project	id	ID	#REQUIRED>
	
	<!ELEMENT goal		(#PCDATA)>

	<!ELEMENT team_member EMPTY>
	<!ATTLIST team_member person IDREF #REQUIRED>

	<!ELEMENT employee	(name)>
	<!ATTLIST employee social_security_number	ID	#REQUIRED>

	<!ELEMENT name	(#PCDATA)>
]>
<top>
	<project id="p1">
		<goal>Develop Strategic Plan</goal>
		<!-- the refered person id must exist in document -->
		<team_member person="ss087-05-1120" />
		<team_member person="ss987-65-4320" />
	</project>
	<project id="p2">
		<goal>Deploy Linux</goal>
		<team_member person="ss087-05-1120" />
		<team_member person="ss9876-12-3456" />
	</project>
	<!-- the ID is unique in document -->
	<employee social_security_number="ss087-05-1120">
		<name>Fred Smith</name>
	</employee>
	<employee social_security_number="ss987-65-4320">
		<name>Jill Jones</name>
	</employee>
	<employee social_security_number="ss9876-12-3456">
		<name>Sydney Lee</name>
	</employee>
</top>
